In [16]:
import numpy as np

ndarray = np.array([[1,2],[3,4],[5,6]])
print(ndarray)

[[1 2]
 [3 4]
 [5 6]]


In [3]:
print(ndarray[1][0])
print(ndarray[1,0])

3
3


In [5]:
array1 = np.array([[1,2,3,4],[2,4,6,4],[3,5,7,8],[4,2,7,4]])
array1

array([[1, 2, 3, 4],
       [2, 4, 6, 4],
       [3, 5, 7, 8],
       [4, 2, 7, 4]])

In [15]:
array1[:,2:]

array([[3, 4],
       [6, 4],
       [7, 8],
       [7, 4]])