# Numpy
Numerical python

In [3]:
import numpy as np

In [4]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

## Numpy Arrays(ndarray)

In [5]:
np.array(
    [1, 2, 3]
)

array([1, 2, 3])

In [6]:
np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
)

In [8]:
matrix[0][1]

2

In [10]:
type(matrix)

numpy.ndarray

In [11]:
type(matrix[0][1])

numpy.int64

In [12]:
type(1)

int

In [16]:
matrix2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    
],
    dtype=complex
)

In [17]:
matrix2

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [19]:
type(matrix2[0][0])

numpy.complex128

In [21]:
ndarray = np.array([1,2,4], dtype=np.uint8) # unsigned + ^ intger 8bit

In [22]:
ndarray

array([1, 2, 4], dtype=uint8)

In [24]:
type(ndarray[0])

numpy.uint8

In [25]:
ndarray2 = np.array([1,2,4], dtype=np.float32) # float 32

In [26]:
ndarray2

array([1., 2., 4.], dtype=float32)

In [27]:
ndarray2.astype(np.uint8)

array([1, 2, 4], dtype=uint8)

In [29]:
array1 = np.array([[1, 2, 3,], [ 4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3,], [ 4, 5, 6], [7, 8, 9]])

In [30]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [34]:
array1 * array2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [35]:
array1 / array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
a = [1, 2, 3]
b = [1, 2, 3]

In [37]:
a + b

[1, 2, 3, 1, 2, 3]

In [38]:
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [39]:
array3 = np.array([1, 2, 3])

In [40]:
array1 + array3

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [41]:
array2 + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
array4 = np.array([1])

In [46]:
array1 + array4

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [47]:
array5 = np.array([1,2])

In [48]:
array1 + array5

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [49]:
ndarray = np.array([[1, 2],[3, 4], [5, 6]])

In [50]:
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
ndarray.shape

(3, 2)

In [52]:
ndarray.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [53]:
ndarray.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [54]:
ndarray.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
ndarray1 = np.array([1, 2, 3])
ndarray2 = np.array([[1, 2, 3]])

In [58]:
print(ndarray1)

[1 2 3]


In [59]:
print(ndarray2)

[[1 2 3]]


In [60]:
ndarray1 + ndarray2

array([[2, 4, 6]])

In [61]:
ndarray2 + ndarray1

array([[2, 4, 6]])

In [62]:
print(ndarray1.shape)

(3,)


In [63]:
print(ndarray2.shape)

(1, 3)


In [65]:
np.expand_dims(ndarray1, axis=0)

array([[1, 2, 3]])

In [66]:
np.expand_dims(ndarray1, axis=0).shape

(1, 3)

In [67]:
np.expand_dims(ndarray1, axis=1)

array([[1],
       [2],
       [3]])

In [69]:
np.expand_dims(ndarray1, axis=-1) # append to last

array([[1],
       [2],
       [3]])

In [70]:
expand_array = np.expand_dims(ndarray1, axis=1)

In [71]:
np.squeeze(expand_array)

array([1, 2, 3])

In [73]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [74]:
ndarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
np.squeeze(ndarray)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
ndarray.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.expand_dims(ndarray, axis=1,)

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])