In [1]:
import numpy as np

In [2]:
np.random.rand()

0.16172255549842907

In [3]:
np.random.rand()

0.23264694908646188

In [4]:
np.random.rand(3)

array([0.95304103, 0.81739122, 0.32677285])

In [10]:
np.random.rand(3, 4)

array([[0.67947882, 0.30575034, 0.3593707 , 0.71319615],
       [0.79931993, 0.79158506, 0.34826665, 0.24574557],
       [0.37867745, 0.47708752, 0.36330013, 0.46182558]])

In [18]:
np.random.seed(1)
np.random.rand(3, 4)

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01, 4.19194514e-01, 6.85219500e-01]])

In [19]:
np.random.rand(3, 4)

array([[0.20445225, 0.87811744, 0.02738759, 0.67046751],
       [0.4173048 , 0.55868983, 0.14038694, 0.19810149],
       [0.80074457, 0.96826158, 0.31342418, 0.69232262]])

In [29]:
np.random.randn(10, 10)

array([[ 2.18557541, -1.39649634, -1.44411381, -0.50446586,  0.16003707,
         0.87616892,  0.31563495, -2.02220122, -0.30620401,  0.82797464],
       [ 0.23009474,  0.76201118, -0.22232814, -0.20075807,  0.18656139,
         0.41005165,  0.19829972,  0.11900865, -0.67066229,  0.37756379],
       [ 0.12182127,  1.12948391,  1.19891788,  0.18515642, -0.37528495,
        -0.63873041,  0.42349435,  0.07734007, -0.34385368,  0.04359686],
       [-0.62000084,  0.69803203, -0.44712856,  1.2245077 ,  0.40349164,
         0.59357852, -1.09491185,  0.16938243,  0.74055645, -0.9537006 ],
       [-0.26621851,  0.03261455, -1.37311732,  0.31515939,  0.84616065,
        -0.85951594,  0.35054598, -1.31228341, -0.03869551, -1.61577235],
       [ 1.12141771,  0.40890054, -0.02461696, -0.77516162,  1.27375593,
         1.96710175, -1.85798186,  1.23616403,  1.62765075,  0.3380117 ],
       [-1.19926803,  0.86334532, -0.1809203 , -0.60392063, -1.23005814,
         0.5505375 ,  0.79280687, -0.62353073

In [55]:
np.random.normal(10, 1, (3, 3))

array([[10.43816635, 11.12232832,  9.0029802 ],
       [ 9.89320601, 11.45142926,  9.38196315],
       [ 7.96279877,  8.05741082,  7.49355935]])

In [60]:
np.random.randint(-3, 3, (3, 4))

array([[ 1, -2, -2,  2],
       [-2, -1,  1,  0],
       [-1,  0,  0, -1]])

In [74]:
for i in range(10):
    print(np.random.randint(i+1))

0
0
1
0
3
1
4
0
8
8


In [75]:
array_list = [1, 2, 3]
np.random.choice(array_list)

3

In [80]:
index_pool = np.arange(0, 10, 2)

In [81]:
index_pool

array([0, 2, 4, 6, 8])

In [82]:
np.random.choice(index_pool)

4