In [1]:
import numpy as np
import pandas as pd 

In [62]:
## np.clip()
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.clip(array, 3, 5)

array([3, 3, 3, 3, 4, 5, 5, 5, 5, 5])

In [64]:
list(set(np.clip(array, 3, 5)))

[3, 4, 5]

In [65]:
1e-4

0.0001

In [66]:
# numpy array condition

In [67]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
## np.whare

In [69]:
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [70]:
np.where(array > 3)

(array([4, 5, 6, 7, 8, 9]),)

In [71]:
# tuple unpack
result, = np.where(array > 3)
result

array([4, 5, 6, 7, 8, 9])

In [72]:
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [73]:
array + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [74]:
array[array>3]

array([4, 5, 6, 7, 8, 9])

In [75]:
array[0] > 3

False

In [76]:
ndarray = array.reshape(2, 5)
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
ndarray[ndarray>3]

array([4, 5, 6, 7, 8, 9])

In [32]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [77]:
(ndarray > 3).all()

False

In [78]:
(ndarray > 3).any()

True

In [79]:
(ndarray > 3).all(axis=0)

array([False, False, False, False,  True])

In [80]:
(ndarray > 3).any(axis=1)

array([ True,  True])

In [81]:
## npuniqe()

In [82]:
array2 = np.array([1, 1, 2, 2, 3, 4, 5, 6, 6, 7, 8, 8, 8])
array2

array([1, 1, 2, 2, 3, 4, 5, 6, 6, 7, 8, 8, 8])

In [83]:
np.unique(array2)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [84]:
np.unique(array2, return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8]), array([2, 2, 1, 1, 1, 2, 1, 3]))

In [57]:
result_1,result_2 = np.unique(array2, return_counts=True)

In [58]:
result_1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
result_2

array([2, 2, 1, 1, 1, 2, 1, 3])