In [1]:
import numpy as np
import pandas as pd 

In [3]:
## np.clip()
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.clip(array, 3, 5)

array([3, 3, 3, 3, 4, 5, 5, 5, 5, 5])

In [9]:
list(set(np.clip(array, 3, 5)))

[3, 4, 5]

In [10]:
1e-4

0.0001

In [11]:
# numpy array condition

In [12]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
## np.whare

In [16]:
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [19]:
np.where(array > 3)

(array([4, 5, 6, 7, 8, 9]),)

In [28]:
# tuple unpack
result, = np.where(array > 3)
result

array([4, 5, 6, 7, 8, 9])

In [20]:
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [21]:
array + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
array[array>3]

array([4, 5, 6, 7, 8, 9])

In [24]:
array[0] > 3

False

In [29]:
ndarray = array.reshape(2, 5)
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
ndarray[ndarray>3]

array([4, 5, 6, 7, 8, 9])

In [32]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [39]:
(ndarray > 3).all()

False

In [43]:
(ndarray > 3).any()

True

In [44]:
(ndarray > 3).all(axis=0)

array([False, False, False, False,  True])

In [45]:
(ndarray > 3).any(axis=1)

array([ True,  True])

In [46]:
## npuniqe()

In [47]:
array2 = np.array([1, 1, 2, 2, 3, 4, 5, 6, 6, 7, 8, 8, 8])
array2

array([1, 1, 2, 2, 3, 4, 5, 6, 6, 7, 8, 8, 8])

In [50]:
np.unique(array2)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
np.unique(array2, return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8]), array([2, 2, 1, 1, 1, 2, 1, 3]))

In [57]:
result_1,result_2 = np.unique(array2, return_counts=True)

In [58]:
result_1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
result_2

array([2, 2, 1, 1, 1, 2, 1, 3])