In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
matrix[0]

array([1, 2, 3])

In [6]:
matrix[0][1]

2

In [7]:
type(matrix[0][1])

numpy.int64

In [8]:
type(1)

int

In [9]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=complex)

In [10]:
type(matrix[0][1])

numpy.complex128

In [12]:
ndarray = np.array([1, 2, 3], dtype=np.uint8) # unsigned + -integer 8bit 0 - 255

In [15]:
np.array([1, 2, 256], dtype=np.uint8)

array([1, 2, 0], dtype=uint8)

In [16]:
np.array([1, 2, 255], dtype=np.uint8)

array([  1,   2, 255], dtype=uint8)

In [17]:
np.array([1, 2, 510], dtype=np.uint8)

array([  1,   2, 254], dtype=uint8)

In [21]:
ndarray.astype(np.float64)

array([1., 2., 3.])

In [22]:
type(ndarray[0])

numpy.uint8