In [1]:
import numpy as np

In [2]:
np.random.randn(5, 5)

array([[ 1.82711113,  0.49072621, -0.63053616, -0.13974029, -0.22449553],
       [ 1.09468499, -1.42395709,  0.84920398, -1.59522943, -0.31124034],
       [ 3.28915396, -1.16628451,  0.41358189, -0.83730995, -0.89303532],
       [ 1.32011587, -0.10615188,  1.77959295,  1.79689618, -0.05967301],
       [ 0.20253045,  0.88539457,  1.41274451,  0.21164775, -0.54824193]])

In [11]:
std_norm = np.random.randn(5, 5)
std_norm

array([[-0.26133612, -0.5498425 ,  0.40833994,  0.99082267,  0.70439562],
       [ 0.30825694, -0.13891686, -0.19004796, -1.27628992,  0.48008539],
       [-0.68209437, -0.71934599,  0.46091072, -1.02223094,  1.52916811],
       [ 0.66049363,  0.76722623, -0.84141532, -0.79454067, -2.14340729],
       [ 0.21499015, -0.00834744,  1.99432226,  2.02304529, -0.7953205 ]])

In [14]:
std_norm.max()

1.177915611435836

In [15]:
np.max(std_norm)

1.177915611435836

In [16]:
std_norm.min()

-1.1318548500410437

In [17]:
std_norm.argmax()

16

In [19]:
std_norm.flatten()[16]

1.177915611435836

In [20]:
std_norm.argmin()

10

In [21]:
std_norm.argsort()

array([[1, 3, 4, 2, 0],
       [4, 2, 0, 3, 1],
       [0, 4, 1, 3, 2],
       [4, 2, 3, 0, 1],
       [4, 3, 1, 0, 2]])

In [25]:
std_norm.mean()

0.019669742973665975

In [26]:
np.random.randn(100,100).mean()

0.006752733385875222

In [27]:
std_norm.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [28]:
np.median(std_norm)

0.07439295277667723

In [32]:
a = [1,2,3]

In [37]:
import statistics

In [38]:
statistics.mean(a)

2

In [40]:
statistics.mean(std_norm.flatten())

0.01966974297366597

In [2]:
a = np.random.randn(1000,10000)

In [3]:
np.median(a)

0.00033266660136945035

In [4]:
np.mean(a)

0.00020912966454534612

In [5]:
import time

In [6]:
before = time.time()
np.median(a)
after = time.time()
after - before

0.3218808174133301

In [7]:
before = time.time()
np.mean(a)
after = time.time()
after - before

0.014075279235839844

In [8]:
np.std(a)

0.9998943544848286

In [12]:
std_norm.max(axis=0)

array([0.66049363, 0.76722623, 1.99432226, 2.02304529, 1.52916811])

In [13]:
std_norm.max(axis=1)

array([0.99082267, 0.48008539, 1.52916811, 0.76722623, 2.02304529])

In [14]:
std_norm

array([[-0.26133612, -0.5498425 ,  0.40833994,  0.99082267,  0.70439562],
       [ 0.30825694, -0.13891686, -0.19004796, -1.27628992,  0.48008539],
       [-0.68209437, -0.71934599,  0.46091072, -1.02223094,  1.52916811],
       [ 0.66049363,  0.76722623, -0.84141532, -0.79454067, -2.14340729],
       [ 0.21499015, -0.00834744,  1.99432226,  2.02304529, -0.7953205 ]])