In [1]:
import numpy as np

In [4]:
np.sqrt([1,2,3,4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

# Log
- 2?=8
  - ?=3
  - ? 指数
  - log2 8 = log2 2 3 = 3log2 2 = 3

y = a x

y'  = ax loge a

In [5]:
np.random.randn(3)

array([-0.5387692 ,  1.83688288,  1.93612827])

In [6]:
np.log(1)

0.0

In [7]:
np.log(2)

0.6931471805599453

In [8]:
x = np.linspace(1,10, 10)

In [9]:
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [11]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [16]:
# 指数関数 eの自乗
np.exp(1)

2.718281828459045

In [17]:
np.exp(2)

7.38905609893065

In [18]:
# ネイピア数
np.e

2.718281828459045

In [19]:
np.sum(np.linspace(1,10,10))

55.0

In [22]:
np.sum(np.arange(1,11))

55

In [23]:
np.sum(np.arange(1,20,2))

100

In [24]:
array = np.arange(1,11)

In [25]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
array.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [28]:
ndarray = array.reshape(2,5)

In [29]:
np.sum(ndarray, axis=0)

array([ 7,  9, 11, 13, 15])

In [30]:
# 1絶対時 absolute value
array = np.arange(-10,0)
array

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [31]:
np.abs(array)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])