In [2]:
import numpy as np

In [3]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.clip(array, 3 ,7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

In [6]:
1e-4

0.0001

# condition

In [7]:
## np.where
np.where(array > 3)

(array([4, 5, 6, 7, 8, 9]),)

In [11]:
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [12]:
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [13]:
array + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
array[array>3]

array([4, 5, 6, 7, 8, 9])

In [17]:
ndarray = array.reshape(2,5)
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
ndarray[ndarray>3]

array([4, 5, 6, 7, 8, 9])

In [20]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [22]:
(ndarray > 3).all()

False

In [23]:
(ndarray > 3).any()

True

In [24]:
array = np.array([1,2,2,2,4,5,6,65,4,3])
array

array([ 1,  2,  2,  2,  4,  5,  6, 65,  4,  3])

In [25]:
np.unique(array)

array([ 1,  2,  3,  4,  5,  6, 65])

In [26]:
np.unique(array, return_counts=True)

(array([ 1,  2,  3,  4,  5,  6, 65]), array([1, 3, 1, 2, 1, 1, 1]))

In [27]:
np.bincount(array)

array([0, 1, 3, 1, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])