In [1]:
import numpy as np

In [10]:
ndarray_even = np.arange(0, 18, 2).reshape(3,3)

In [11]:
nparray_even

NameError: name 'nparray_even' is not defined

In [12]:
ndarray_odd = np.arange(1,19,2).reshape(3,3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [13]:
np.concatenate([ndarray_even,ndarray_odd])

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [15]:
np.concatenate([ndarray_even,ndarray_odd],axis=1)

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

In [16]:
np.stack([ndarray_even,ndarray_odd])

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [18]:
stacked_array = _

In [19]:
stacked_array

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [20]:
stacked_array.shape

(2, 3, 3)

In [21]:
np.stack([ndarray_even,ndarray_odd],axis=0).shape

(2, 3, 3)

In [22]:
np.stack([ndarray_even,ndarray_odd],axis=1).shape

(3, 2, 3)

In [23]:
np.stack([ndarray_even,ndarray_odd],axis=2).shape

(3, 3, 2)

In [24]:
np.stack([ndarray_even,ndarray_odd],axis=-1).shape

(3, 3, 2)

In [25]:
np.stack([ndarray_even,ndarray_odd],axis=-1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [26]:
ndarray = np.random.randn(3, 4)
ndarray

array([[ 0.50198825, -1.81136491, -0.9683517 , -0.71297007],
       [-1.36164088,  1.19565426, -0.74662797,  0.2100581 ],
       [ 0.78214717, -0.26711799,  1.52884531, -0.30997676]])

In [27]:
ndarray.shape

(3, 4)

In [29]:
np.transpose(ndarray).shape

(4, 3)

In [30]:
np.transpose(ndarray)

array([[ 0.50198825, -1.36164088,  0.78214717],
       [-1.81136491,  1.19565426, -0.26711799],
       [-0.9683517 , -0.74662797,  1.52884531],
       [-0.71297007,  0.2100581 , -0.30997676]])

In [31]:
ndarray.T

array([[ 0.50198825, -1.36164088,  0.78214717],
       [-1.81136491,  1.19565426, -0.26711799],
       [-0.9683517 , -0.74662797,  1.52884531],
       [-0.71297007,  0.2100581 , -0.30997676]])

In [32]:
ndarray = np.random.randn(3,4,5)

In [33]:
ndarray.T.shape

(5, 4, 3)