In [1]:
import numpy

In [2]:
numpy.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

In [3]:
import numpy as np

In [4]:
python_list = [1,2,3]
python_list

[1, 2, 3]

In [5]:
np_list = np.array([1,2,3])
np_list

array([1, 2, 3])

In [6]:
python_list = [[1,2,3],[4,5,6],[7,8,9]]
python_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np_list = np.array([[1,2,3],[1,2,3],[1,2,3]])
np_list

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [9]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [11]:
array1 * array2 

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [12]:
array1 / array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
array3 = np.array([1,2,3])
array4 = np.array([[1,2,3],[4,5,6],[7,8,9]])

array3 + array4

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [14]:
array5 = np.array([1,2,3,4])
array6 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array5 * array6

ValueError: operands could not be broadcast together with shapes (4,) (3,3) 

In [19]:
array7 = np.array([[1,2],[3,4],[5,6]])
print(array7)
array7.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)