In [2]:
import numpy as np
ndarray = np.array([1,2,3])
print(ndarray)

[1 2 3]


In [3]:
np.arange(0,5,2)

array([0, 2, 4])

In [4]:
np.arange(5)
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [48]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [11]:
ndarray2 = np.arange(0,5)
print(ndarray2)
ndarray3 = ndarray2.copy()
print(id(ndarray2))
print(id(ndarray3))
ndarray2[:] = 100
print(ndarray2)

[0 1 2 3 4]
139706098862880
139706098863520
[100 100 100 100 100]


In [12]:
def add_world(hello):
    hello += ' world'
    return hello


In [13]:
h_str = 'hello'
h_list = ['h','e','l','l','o']
output_str = add_world(h_str)
output_list = add_world(h_list)

In [14]:
print(output_str)
print(output_list)
print(h_str)
print(h_list)

hello world
['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']
hello
['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']


In [7]:
def change_hundred(array):
    array[0] = 100
    return array

def change_hundred_copy(array):
    array_copy = array.copy()
    array_copy[0] = 100
    return array_copy

array_1 = np.arange(0,4)
array_2 = np.arange(0,4)

output_array1 = change_hundred(array_1)
print(array_1)
output_array_copy1 = change_hundred_copy(array_2)
print(array_2)

[100   1   2   3]
[0 1 2 3]


In [9]:
shape1 = (2,3,5)
zeros = np.zeros(shape1)
print(zeros)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [12]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [18]:
shape2 = (2,3,5)
one_arrays1 = np.ones(shape2)
print(one_arrays1)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [20]:
one_arrays2 = np.ones(5)
print(one_arrays2)

[1. 1. 1. 1. 1.]


In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(5,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
np.random.rand()

0.7745296627451715

In [29]:
np.random.rand(2)

array([0.129079 , 0.3236071])

In [30]:
np.random.rand(3,5)

array([[0.87609441, 0.30471612, 0.82433195, 0.39648513, 0.93708571],
       [0.85734646, 0.17708369, 0.52024578, 0.02458406, 0.66250898],
       [0.07793927, 0.3293324 , 0.44494375, 0.44578115, 0.10243597]])

In [31]:
np.random.randn()

0.8735415645312189

In [32]:
np.random.randn(3)

array([-0.94823082,  0.10002513,  0.74626504])

In [51]:
np.random.randint(10,50, size=(2,5,20))

array([[[31, 21, 10, 30, 25, 22, 13, 49, 30, 45, 29, 16, 14, 37, 15, 27,
         39, 24, 39, 46],
        [42, 20, 41, 31, 19, 38, 31, 27, 17, 33, 32, 15, 44, 21, 49, 31,
         34, 41, 39, 39],
        [20, 15, 41, 44, 45, 24, 25, 32, 45, 28, 17, 37, 35, 41, 35, 18,
         40, 40, 13, 49],
        [47, 48, 40, 28, 40, 22, 20, 10, 20, 10, 41, 17, 30, 47, 34, 29,
         35, 31, 10, 28],
        [36, 32, 10, 14, 16, 42, 11, 10, 20, 27, 23, 45, 43, 22, 35, 33,
         34, 22, 41, 28]],

       [[25, 43, 39, 30, 12, 33, 10, 29, 32, 44, 36, 34, 45, 43, 12, 15,
         47, 19, 12, 15],
        [22, 34, 29, 27, 17, 25, 24, 34, 38, 41, 21, 40, 10, 30, 21, 19,
         34, 12, 10, 21],
        [16, 44, 35, 12, 24, 33, 23, 14, 32, 42, 30, 36, 30, 46, 42, 32,
         34, 41, 26, 29],
        [42, 32, 32, 28, 47, 42, 16, 15, 27, 22, 38, 15, 24, 41, 12, 46,
         27, 27, 43, 43],
        [13, 34, 25, 23, 18, 47, 40, 46, 21, 18, 24, 17, 43, 22, 34, 10,
         30, 37, 20, 49]]])

In [37]:
array5 = np.arange(0,10)
print(array5)

[0 1 2 3 4 5 6 7 8 9]


In [41]:
new_shape = (2,5)
print(new_shape)

(2, 5)


In [39]:
type(new_shape)

tuple

In [44]:
reshaped_array = array5.reshape(new_shape)
print(reshaped_array)
type(reshaped_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


numpy.ndarray

In [47]:
array6 = np.arange(1,22)
print(array6.reshape((3,7)))

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
