In [1]:
# 平方根 square root
import numpy as np

In [3]:
np.sqrt([1, 2, 3, 4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [4]:
np.log(1)

0.0

In [5]:
np.log(2)

0.6931471805599453

In [6]:
x = np.linspace(1, 10, 10)

In [7]:
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
type(x)

numpy.ndarray

In [9]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [10]:
np.log2(x)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809])

In [11]:
# 指数関数 exponetinal tial funcion
np.exp(2)

7.38905609893065

In [12]:
np.exp(1)

2.718281828459045

In [13]:
2.718281828459045 ** 2

7.3890560989306495

In [14]:
np.e

2.718281828459045

In [15]:
# 合計 summation
np.sum([1, 2, 3])

6

In [16]:
np.sum(x)

55.0

In [21]:
np.sum(np.arange(1, 11))

55

In [28]:
np.arange(1, 11).reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
np.sum(np.arange(1, 11).reshape(2, 5),axis=0)

array([ 7,  9, 11, 13, 15])

In [32]:
np.sum(np.arange(1, 11).reshape(2, 5),axis=1)

array([15, 40])

In [33]:
# 絶対値 absolute value
np.arange(-10, 0)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [42]:
np.abs(np.arange(-10, 0))

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [46]:
np.log(2)

0.6931471805599453