In [1]:
import numpy as np

In [3]:
np.arange(0, 18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [4]:
np.arange(0, 18, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [5]:
np.linspace(0, 18, 2)

array([ 0., 18.])

In [7]:
np.arange(0, 18, 2).reshape(3, 3)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [8]:
ndarray_even = np.arange(0, 18, 2).reshape(3, 3)

In [9]:
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [13]:
ndarray_odd = np.arange(1, 19, 2).reshape(3, 3)

In [14]:
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [16]:
np.concatenate([ndarray_even, ndarray_odd])

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [29]:
np.concatenate([ndarray_even, ndarray_odd], axis=1)

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

In [31]:
np.stack([ndarray_even, ndarray_odd], axis=0)

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [32]:
np.stack([ndarray_even, ndarray_odd], axis=1)

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]],

       [[12, 14, 16],
        [13, 15, 17]]])

In [33]:
np.stack([ndarray_even, ndarray_odd], axis=2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [34]:
np.stack([ndarray_even, ndarray_odd], axis=-1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [21]:
stacked_array = _

In [26]:
stacked_array.shape

(2, 3, 3)

In [35]:
ndarray = np.random.randn(3, 4)
ndarray 

array([[-0.51221888,  0.9943301 , -0.78777693,  0.66019471],
       [-0.47623032,  0.83375599,  0.57857786, -0.9130197 ],
       [ 1.19619485,  1.5360956 , -0.03883277, -0.00553674]])

In [36]:
ndarray.shape

(3, 4)

In [38]:
np.transpose(ndarray)

array([[-0.51221888, -0.47623032,  1.19619485],
       [ 0.9943301 ,  0.83375599,  1.5360956 ],
       [-0.78777693,  0.57857786, -0.03883277],
       [ 0.66019471, -0.9130197 , -0.00553674]])

In [39]:
transpose_ndarray = _

In [40]:
transpose_ndarray.shape

(4, 3)

In [41]:
ndarray.T

array([[-0.51221888, -0.47623032,  1.19619485],
       [ 0.9943301 ,  0.83375599,  1.5360956 ],
       [-0.78777693,  0.57857786, -0.03883277],
       [ 0.66019471, -0.9130197 , -0.00553674]])

In [42]:
ndarray = np.random.rand(3, 4, 5)

In [43]:
ndarray

array([[[0.99679259, 0.58121224, 0.29487935, 0.52478788, 0.07726425],
        [0.68037961, 0.96104494, 0.23562747, 0.97063714, 0.74432157],
        [0.73515824, 0.14285229, 0.76350556, 0.75651278, 0.78708836],
        [0.45342889, 0.27906396, 0.21112484, 0.83673054, 0.60691173]],

       [[0.50509015, 0.22516211, 0.12174088, 0.22523979, 0.95958868],
        [0.80861179, 0.47875708, 0.96991072, 0.12587218, 0.56670317],
        [0.56013259, 0.84845006, 0.52885024, 0.05156159, 0.85636921],
        [0.77318384, 0.41614563, 0.61254917, 0.01353902, 0.5290732 ]],

       [[0.74584091, 0.18375651, 0.97338565, 0.31320351, 0.92744155],
        [0.72438189, 0.31194078, 0.11758832, 0.07073098, 0.89679746],
        [0.8656494 , 0.57855993, 0.20083927, 0.65198137, 0.93815081],
        [0.1861623 , 0.14251964, 0.63146357, 0.35732058, 0.00322182]]])

In [44]:
ndarray.shape

(3, 4, 5)

In [45]:
ndarray.T.shape

(5, 4, 3)