In [1]:
import numpy
numpy.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

In [1]:
import numpy as np
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

In [2]:
p_l = [1,2,3]
p_l

[1, 2, 3]

In [3]:
n_l = np.array([1,2,3])
n_l

array([1, 2, 3])

In [4]:
p_l2 = [[1,2,3],[4,5,6],[7,8,9]]
p_l2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
n_l2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
n_l2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
n_l3 =  np.array([[1,2,3],[4,5,6],[7,8,9]])
n_l4 =  np.array([[1,2,3],[4,5,6],[7,8,9]])
n_l3 + n_l4

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [8]:
n_l5 = np.array([1,2,3])

n_l3 + n_l5

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [9]:
n_l6 = np.array([1,2,3,4])
n_l3 + nl_6

NameError: name 'nl_6' is not defined

In [10]:
print(n_l3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
n_l3.shape

(3, 3)