In [1]:
import numpy as np

In [2]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
type(np.array([1, 2, 3]))

numpy.ndarray

In [5]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [7]:
matrix[0][1]

2

In [8]:
type(matrix)

numpy.ndarray

In [9]:
type(matrix[0])

numpy.ndarray

In [10]:
type(matrix[0][0])

numpy.int64

In [11]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=complex)

In [12]:
matrix

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [15]:
type(matrix[0][0])

numpy.complex128

- complex = 複素数
- uint8 = 0 - 255 (2 ^ 8)
- float32 (64bitのままだとデータがでかいため、32bitにして保存することが多い)

In [20]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.uint8)

In [21]:
type(matrix[0][0])

numpy.uint8

In [22]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=uint8)

In [23]:
matrix.astype(np.float32)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [25]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [26]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [27]:
array1 * array2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [29]:
array3 = np.array([1, 2, 3])

In [30]:
array1 + array3

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [31]:
array4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [35]:
array4 + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [36]:
array1 + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [38]:
array4.shape

(3, 3)

In [40]:
array4.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [42]:
array4.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [43]:
np.array([1,2,3]).shape

(3,)

In [44]:
np.array([[1,2,3]]).shape

(1, 3)

In [48]:
ndarray1 = np.array([1,2,3])

In [49]:
np.expand_dims(ndarray1, axis=0)

array([[1, 2, 3]])

In [50]:
np.expand_dims(ndarray1, axis=1)

array([[1],
       [2],
       [3]])

In [51]:
ndarray2 = np.expand_dims(ndarray1, axis=1)

In [54]:
ndarray1.shape

(3,)

In [55]:
ndarray2.shape

(3, 1)

In [56]:
np.squeeze(ndarray2)

array([1, 2, 3])

In [57]:
np.squeeze(ndarray2).shape

(3,)

In [60]:
ndarray3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [61]:
ndarray3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
ndarray3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Indexing and slicing

In [65]:
ndarray5 = np.array([1,2,3,4])

In [66]:
ndarray5[0]

1

In [67]:
ndarray6 = np.array([[1, 2], [3, 4], [5, 6]])

In [68]:
ndarray6[0]

array([1, 2])

In [69]:
ndarray6[0][1]

2

In [71]:
ndarray6[0,1]

2

In [73]:
ndarray6[1:]

array([[3, 4],
       [5, 6]])

In [74]:
ndarray6[1:2]

array([[3, 4]])

In [77]:
ndarray6[1:2, 0:1]

array([[3]])

In [84]:
ndarray6[-2:-1]

array([[3, 4]])

# arange linspace logspace

In [88]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [90]:
np.arange(10,20, 2)

array([10, 12, 14, 16, 18])

In [94]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [95]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [99]:
np.logspace(0, 3, 10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [100]:
np.linspace(0, 3, 10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [101]:
10 ** 0.33333333

2.1544346734959863

In [104]:
np.logspace(0, 3, 10, endpoint=False)

array([  1.        ,   1.99526231,   3.98107171,   7.94328235,
        15.84893192,  31.6227766 ,  63.09573445, 125.89254118,
       251.18864315, 501.18723363])

# zeros ones eye

In [107]:
np.zeros([1, 3], dtype=np.int8,)

array([[0, 0, 0]], dtype=int8)

In [111]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [112]:
np.ones([3,3])*5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [114]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [115]:
np.eye(3, 6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [116]:
np.eye(3, 6) * 5

array([[5., 0., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0., 0.],
       [0., 0., 5., 0., 0., 0.]])

# random

In [118]:
np.random.rand(3, 5)

array([[0.96709215, 0.39646801, 0.06278052, 0.34694603, 0.86020571],
       [0.79050571, 0.45836501, 0.87912822, 0.49452215, 0.60481259],
       [0.63719849, 0.66409084, 0.62087763, 0.10258959, 0.09744214]])

In [120]:

np.random.rand(3, 5)

array([[0.86296247, 0.49906597, 0.6954464 , 0.25966586, 0.56727784],
       [0.13174124, 0.17787751, 0.47873968, 0.6716681 , 0.96170103],
       [0.03142517, 0.81538511, 0.95995046, 0.31027119, 0.47051021]])

In [121]:
np.random.rand(3, 5)

array([[0.20496194, 0.34383807, 0.06326104, 0.63436343, 0.82932298],
       [0.05862025, 0.07030529, 0.75830012, 0.04878189, 0.98394995],
       [0.39716562, 0.03728865, 0.69161054, 0.64717297, 0.77842554]])

In [125]:
np.random.seed(1)

In [126]:
np.random.rand(3, 5)

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01],
       [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01,
        5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02]])

In [127]:
np.random.seed(1)

In [128]:
np.random.rand(3, 5)

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01],
       [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01,
        5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02]])

In [133]:
np.random.randn(2, 3)

array([[ 0.56434487, -0.56651023,  0.7299756 ],
       [ 0.37299379,  0.53381091, -0.0919733 ]])

In [135]:
np.random.normal(10, 1)

10.330797129652892

In [142]:
np.random.randint(10, 100, (10, 10))

array([[53, 86, 36, 62, 90, 51, 92, 25, 74, 78],
       [35, 97, 17, 36, 35, 32, 19, 77, 33, 37],
       [47, 67, 93, 48, 18, 42, 44, 20, 33, 25],
       [97, 35, 81, 84, 72, 56, 42, 98, 33, 65],
       [75, 87, 13, 10, 87, 16, 62, 95, 80, 12],
       [86, 31, 85, 17, 87, 82, 85, 86, 53, 30],
       [40, 46, 17, 55, 78, 67, 92, 23, 20, 33],
       [91, 17, 34, 84, 30, 42, 22, 75, 70, 34],
       [92, 12, 20, 64, 92, 96, 80, 76, 81, 58],
       [64, 25, 15, 27, 52, 30, 58, 32, 23, 63]])

In [147]:
a = [1,2,3]
np.random.choice(a)

3

# 統計量

In [148]:
std_norm = np.random.randn(5, 5)

In [149]:
std_norm

array([[-0.22232814, -0.20075807,  0.18656139,  0.41005165,  0.19829972],
       [ 0.11900865, -0.67066229,  0.37756379,  0.12182127,  1.12948391],
       [ 1.19891788,  0.18515642, -0.37528495, -0.63873041,  0.42349435],
       [ 0.07734007, -0.34385368,  0.04359686, -0.62000084,  0.69803203],
       [-0.44712856,  1.2245077 ,  0.40349164,  0.59357852, -1.09491185]])

In [150]:
std_norm.max()

1.2245077048054989

In [152]:
np.max(std_norm)

1.2245077048054989

In [153]:
std_norm.min()

-1.0949118457410418

In [154]:
np.min(std_norm)

-1.0949118457410418

In [155]:
std_norm.argmax()

21

In [157]:
std_norm.flatten()[std_norm.argmax()]

1.2245077048054989

In [159]:
std_norm.mean()

0.11108988257892126

In [164]:
std_norm.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [166]:
np.median(std_norm)

0.12182127099143693

# 標準偏差
- 値から平均との差を２条した合計をデータ数で割ったせいの平方根
  - 値　５
  - 平均が 10
  - 差が-5
  - ２条 -25
  - データ数が３
  - -25 /3 = -8.3333
  - -8.333 の平方根 = 2.888675

In [171]:
np.std(std_norm)

0.5841743777310517

In [172]:
std_norm.max()

1.2245077048054989

In [173]:
std_norm.max(axis=0)

array([1.19891788, 1.2245077 , 0.40349164, 0.59357852, 1.12948391])

In [174]:
std_norm.max(axis=1)

array([0.41005165, 1.12948391, 1.19891788, 0.69803203, 1.2245077 ])

# 平方根 log

In [175]:
np.sqrt([1,2,3,4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [177]:
np.log(2)

0.6931471805599453

In [178]:
x = np.linspace(1,10, 10)

In [179]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

# 指数関数　 exponentinal function

In [180]:
np.exp(1)

2.718281828459045

In [181]:
np.exp(2)

7.38905609893065

In [182]:
2.718281828459045 * 2.718281828459045

7.3890560989306495

In [183]:
np.e

2.718281828459045

# 合計　summation

In [184]:
array = np.arange(1, 11)

In [185]:
np.sum([1,2,3])

6

In [186]:
np.sum(array)

55

In [187]:
array.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [188]:
ndarray = array.reshape(2,5)

In [189]:
np.sum(ndarray, axis=0)

array([ 7,  9, 11, 13, 15])

In [190]:
np.sum(ndarray, axis=1)

array([15, 40])

# 絶対値 absolute value

In [196]:
np.arange(-10, 0)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [197]:
np.abs(np.arange(-10, 0))

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

# NaN

In [198]:
np.log(-10)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


nan

In [199]:
np.nan

nan

In [200]:
type(np.nan)

float

In [201]:
np.isnan(np.log(-10))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


True

In [202]:
a = None
a == None

True

In [203]:
a is None

True

In [204]:
np.log(-10) is np.nan

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


False