In [1]:
import numpy as np

In [2]:
array1 = np.array([[1, 2, 3], [4, 5, 6,], [7, 8, 9]])
array2 = np.array([1, 2, 3])

In [3]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [4]:
array3 = np.array([[1,2],[3,4],[5,6]])

In [5]:
array3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
array3.shape

(3, 2)

In [7]:
array3.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
array3.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [9]:
array3.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [10]:
array4 = np.array([1,2,3])
array5 = np.array([[1,2,3]])

In [11]:
print(array4)
print(array5)

[1 2 3]
[[1 2 3]]


In [12]:
array4.shape

(3,)

In [13]:
array5.shape

(1, 3)

In [14]:
np.expand_dims(array5,axis=0)

array([[[1, 2, 3]]])

In [26]:
np.expand_dims(array5,axis=0).shape

(1, 1, 3)

In [31]:
np.expand_dims(array5,axis=-1).shape

(1, 3, 1)

In [22]:
np.expand_dims(array5,axis=1).shape

(1, 1, 3)

In [23]:
np.expand_dims(array5,axis=1)


array([[[1, 2, 3]]])

In [25]:
np.expand_dims(array5,axis=0).shape

(1, 1, 3)

In [33]:
np.squeeze(array5)

array([1, 2, 3])

In [34]:
array5

array([[1, 2, 3]])

In [35]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
array1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])