In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])

In [3]:
array1

array([1, 2, 3])

In [4]:
array1[-1]

3

In [6]:
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
array2[1][2]

6

In [10]:
array3 = np.array([1,2,3,4])

In [11]:
array3[1:3]

array([2, 3])

In [12]:
array3[:3]

array([1, 2, 3])

In [13]:
array3[3:]

array([4])

In [14]:
array3[-2]

3

In [15]:
array3[-2:]

array([3, 4])

In [16]:
array3[:-2]

array([1, 2])

In [17]:
array4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [18]:
array4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
array4[:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
array4[:3][2:]

array([[ 9, 10, 11, 12]])

In [21]:
array4[:3,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])