In [1]:
import numpy as np

In [3]:
np.random.rand()

0.36900556716116684

In [4]:
np.random.rand(3, 4)

array([[0.08758153, 0.60381829, 0.42199566, 0.85006895],
       [0.27821075, 0.79679307, 0.16659861, 0.54373197],
       [0.13751786, 0.68786686, 0.5784843 , 0.65007567]])

In [7]:
np.random.rand()

0.7216761203418691

In [8]:
np.random.seed(1)
np.random.rand()

0.417022004702574

In [9]:
np.random.rand()

0.7203244934421581

In [13]:
np.random.randn()

-2.3015386968802827

In [22]:
np.random.normal(0, 1)

1.1337694423354374

In [31]:
np.random.randint(3, 100, (2,3))

array([[73, 24, 52],
       [60,  6, 71]])

In [34]:
np.random.choice(10,(3,3))

array([[4, 0, 3],
       [9, 2, 0],
       [4, 9, 2]])